-- ONLINE BOOK STORE SQL PROJECT
-- Created by Maseera

CREATE DATABASE IF NOT EXISTS
online_book_store;

USE online_book_store;

-- =========================================
-- TABLE CREATION
-- =========================================

CREATE TABLE authors (
    author_id INT PRIMARY KEY,
    author_name VARCHAR(100) NOT NULL,
    country VARCHAR(50)
);

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    city VARCHAR(50)
);

CREATE TABLE books (
    book_id INT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    author_id INT,
    price DECIMAL(10,2),
    stock INT,
    FOREIGN KEY (author_id) REFERENCES authors(author_id)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE,
    order_status VARCHAR(30),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    book_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
);

CREATE TABLE payments (
    payment_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    payment_date DATE,
    amount DECIMAL(10,2),
    payment_status VARCHAR(30),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);


-- =========================================
-- INSERT DATA
-- =========================================

INSERT INTO authors (author_id, author_name, country)
VALUES
(1, 'George Orwell', 'United Kingdom'),
(2, 'J.K. Rowling', 'United Kingdom'),
(3, 'Yuval Noah Harari', 'Israel'),
(4, 'James Clear', 'United States'),
(5, 'Robert Kiyosaki', 'United States');

INSERT INTO customers (customer_id, customer_name, email, city)
VALUES
(1, 'Aarav Sharma', 'aarav@gmail.com', 'Mumbai'),
(2, 'Priya Patel', 'priya@gmail.com', 'Pune'),
(3, 'Rahul Verma', 'rahul@gmail.com', 'Delhi'),
(4, 'Sneha Khan', 'sneha@gmail.com', 'Hyderabad'),
(5, 'Arjun Mehta', 'arjun@gmail.com', 'Bangalore'),
(6, 'Neha Singh', 'neha@gmail.com', 'Chennai');

INSERT INTO books (book_id, title, author_id, price, stock)
VALUES
(1, '1984', 1, 450.00, 20),
(2, 'Harry Potter and the Philosopher''s Stone', 2, 550.00, 15),
(3, 'Sapiens', 3, 700.00, 10),
(4, 'Atomic Habits', 4, 600.00, 25),
(5, 'Rich Dad Poor Dad', 5, 500.00, 18),
(6, 'Animal Farm', 1, 350.00, 12),
(7, 'Harry Potter and the Chamber of Secrets', 2, 600.00, 8);

INSERT INTO orders (order_id, customer_id, order_date, order_status)
VALUES
(1, 1, '2026-08-01', 'Completed'),
(2, 2, '2026-08-03', 'Completed'),
(3, 3, '2026-08-05', 'Pending'),
(4, 1, '2026-08-07', 'Completed'),
(5, 4, '2026-08-10', 'Cancelled'),
(6, 5, '2026-08-12', 'Completed'),
(7, 6, '2026-08-15', 'Completed');

INSERT INTO order_items (order_item_id, order_id, book_id, quantity, price)
VALUES
(1, 1, 4, 2, 600.00),
(2, 1, 1, 1, 450.00),
(3, 2, 2, 1, 550.00),
(4, 2, 5, 2, 500.00),
(5, 3, 3, 1, 700.00),
(6, 4, 7, 1, 600.00),
(7, 4, 6, 2, 350.00),
(8, 5, 4, 1, 600.00),
(9, 6, 5, 1, 500.00),
(10, 6, 3, 2, 700.00),
(11, 7, 1, 1, 450.00),
(12, 7, 2, 1, 550.00);

INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_status)
VALUES
(1, 1, '2026-08-01', 1650.00, 'Paid'),
(2, 2, '2026-08-03', 1550.00, 'Paid'),
(3, 3, '2026-08-05', 700.00, 'Pending'),
(4, 4, '2026-08-07', 1300.00, 'Paid'),
(5, 5, '2026-08-10', 600.00, 'Refunded'),
(6, 6, '2026-08-12', 1900.00, 'Paid'),
(7, 7, '2026-08-15', 1000.00, 'Paid');

-- =========================================
-- BUSINESS ANALYSIS
-- =========================================

-- Q1. Display books with their author names and countries

SELECT
    b.title,
    a.author_name,
    a.country,
    b.price
FROM books AS b
INNER JOIN authors AS a
    ON b.author_id = a.author_id;
    
    -- Q2. Find books priced above ₹500

SELECT
    b.title,
    a.author_name,
    b.price
FROM books AS b
INNER JOIN authors AS a
    ON b.author_id = a.author_id
WHERE b.price > 500
ORDER BY b.price DESC;

-- Q3. Count books written by each author

SELECT
    a.author_name,
    COUNT(b.book_id) AS total_books
FROM authors AS a
INNER JOIN books AS b
    ON a.author_id = b.author_id
GROUP BY a.author_name;

-- Q4. Find the top 3 books by quantity sold

SELECT
    b.title,
    SUM(oi.quantity) AS total_quantity_sold
FROM books AS b
INNER JOIN order_items AS oi
    ON b.book_id = oi.book_id
GROUP BY b.title
ORDER BY total_quantity_sold DESC
LIMIT 3;

-- Q5. Calculate revenue generated by each book

SELECT
    b.title,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM books AS b
INNER JOIN order_items AS oi
    ON b.book_id = oi.book_id
GROUP BY b.title
ORDER BY total_revenue DESC;

-- Q6. Find customer spending

SELECT
    c.customer_name,
    SUM(oi.quantity * oi.price) AS total_spending
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_name
ORDER BY total_spending DESC;

-- Q7. Find customers who have never placed an order

SELECT
    c.customer_id,
    c.customer_name
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

-- Q8. Find books that have never been ordered

SELECT
    b.book_id,
    b.title
FROM books AS b
LEFT JOIN order_items AS oi
    ON b.book_id = oi.book_id
WHERE oi.book_id IS NULL;

-- Q9. Calculate revenue from completed orders only

SELECT
    SUM(oi.quantity * oi.price) AS completed_revenue
FROM orders AS o
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed';